US01 cadastro usuário - [fga-eps-mds/2022-2-Schedula-Doc#15] #32
fga-eps-mds/2022-2-schedula-gestor-de-usuarios pull request #5
Opened 2022-12-11 15:14 UTC by MastromauroUnB

# Pull Request US01 Cadastro de usuário

## 📖 Descrição
Neste branch foi desenvolvido o CRUD de Usuários, com endpoints GET, POST, PATCH e DELETE. 

### 🎫 Notas
Apesar da criação de usuários permitir ADMIN como perfil, esse perfil não é considerado em nenhum momento no código para a realização do CRUD.

## 👩‍💻 Reviewer Notes

## Issue Zenhub

Closes fga-eps-mds/2022-2-Schedula-Doc#15

2022-12-11 17:48 UTC, matgomes21 requested changes
Alterar nomes de pastas/funções/variável etc para inglês, para seguirmos o padrão internacional. Ex.: `usuario.entity.ts` -> `user.entity.ts`

2022-12-11 17:50 UTC, matgomes21 commented
Alterar branch `target` de `main` para `develop`

2022-12-11 21:21 UTC, viniciussaturnino requested changes
Tentei bater no endpoint de user e ele deu not found

2022-12-11 21:21 UTC, viniciussaturnino commented on src/users/users.controller.ts
> +  @Patch(':id')
Usar PUT

2022-12-11 22:06 UTC, MastromauroUnB commented on src/users/users.controller.ts
> +  @Patch(':id')
Fiz a correção e adicionei um Get vazio pra retornar todos os usuários

2022-12-12 03:54 UTC, matgomes21 approved these changes
lgtm

2022-12-12 03:54 UTC, merged